---
#
# Task file for deploying zabbix custom scripts to proper location.
#

- name: Create Zabbix folders
  file:
    path={{ item }}
    owner=root
    mode=0755
    state=directory
  with_items:
    - "{{ zabbix_prefix_dir }}/scripts"
    - "{{ zabbix_prefix_dir }}/conf"
    - "{{ zabbix_prefix_dir }}/conf/check_header.conf.d"

- name: Copy Zabbix custom scripts
  template:
    src={{ item }}
    dest={{ zabbix_prefix_dir }}/scripts/{{ item | basename | regex_replace('.j2','') }}
    owner=root
    group=root
    mode=0755
  with_fileglob:
    - templates/agent/scripts/*
  notify: restart zabbix-agent

- name: Copy Zabbix custom scripts config files
  template:
    src={{ item }}
    dest={{ zabbix_prefix_dir }}/conf/{{ item | basename | regex_replace('.j2','') }}
    owner=root
    group=root
    mode=0755
  with_fileglob:
    - templates/agent/conf/*
  notify: restart zabbix-agent

# - name: Copy Zabbix check_header.conf.d scripts config files
#   template:
#     src={{ item }}
#     dest={{ zabbix_prefix_dir }}/conf/check_header.conf.d/{{ item | basename | regex_replace('.j2','') }}
#     owner=root
#     group=root
#     mode=0755
#   with_fileglob:
#     - templates/agent/conf/check_header.conf.d/*

- name: Generate predefined config for check_header
  copy:
    content={{ item.content | to_json }}
    dest={{ zabbix_prefix_dir }}/conf/check_header.conf.d/{{ item.filename }}
  with_items: "{{ check_header_config_list }}"

- name: Copy Zabbix config file for UserParameters
  template:
    src={{ item }}
    dest={{ zabbix_conf_dir }}/zabbix_agentd.d/{{ item | basename | regex_replace('.j2','') }}
    owner=root
    group=root
    mode=0755
  with_fileglob:
    - templates/agent/zabbix-agentd.d/*
  notify: restart zabbix-agent

- include: install-packages.yml
