---
#
# Task file for deploying zabbix custom scripts to proper location.
#

- name: Create Zabbix folders
  file:
    path={{ item }}
    owner=root
    mode=0755
    state=directory
  with_items:
    - "{{ zabbix_prefix_dir }}/scripts"
    - "{{ zabbix_prefix_dir }}/conf"

- name: Copy Zabbix custom scripts
  template:
    src={{ item }}
    dest={{ zabbix_prefix_dir }}/scripts
    owner=root
    group=root
    mode=0755
  with_fileglob:
    - scripts/*
  notify: restart zabbix-agent

- name: Copy Zabbix custom scripts config files
  template:
    src={{ item }}
    dest={{ zabbix_prefix_dir }}/conf
    owner=root
    group=root
    mode=0755
    force=no
  with_fileglob:
    - conf/*
  notify: restart zabbix-agent

- name: Copy Zabbix config file for UserParameters
  template:
    src={{ item }}
    dest={{ zabbix_conf_dir }}/zabbix-agentd.d/
    owner=root
    group=root
    mode=0755
  with_fileglob:
    - zabbix-agentd.d/*
  notify: restart zabbix-agent

